import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import { ThemeProvider } from "@/components/themeprovider";
import { Toaster } from "sonner";
import ClientSessionProvider from "@/components/client-session-provider";
import { ColorThemeProvider } from "@/components/ui/colorPicker";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "time",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/logo_no_bg.png" type="image/png" />
        <link
          href="https://fonts.googleapis.com/css2?family=Great+Vibes&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${inter.className} min-h-screen flex flex-col`}
        suppressHydrationWarning
      >
        <ClientSessionProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
            storageKey="theme-preference"
          >
            <ColorThemeProvider>
              <main className="flex-grow">{children}</main>
              <footer className="mt-auto">
                <Footer />
              </footer>
              <Toaster />
            </ColorThemeProvider>
          </ThemeProvider>
        </ClientSessionProvider>
      </body>
    </html>
  );
}
